apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-build
  namespace: jatinderkumarchaurasia-dev
  labels:
    name: docker-build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-hello-world.git'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk:19-jdk'
        namespace: openshift
      env:
        - name: EXAMPLE
          value: sample-app
  output:
    to:
      kind: ImageStreamTag
      name: 'test-app:latest'
  postCommit:
    args:
      - bundle
      - exec
      - rake
      - test
